model:
  num_classes: 2
  hidden_dim: 512
  attention_layers: 4

train:
  batch_size: 8
  num_epochs: 50
  learning_rate: 0.001
  weight_decay: 0.0001
  save_dir: './checkpoints'

data:
  train_dir: './train'
  test_dir: './test'
  image_size: 512